### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by fxcosta** [jasonroyle/ng2-img-map#1]
Can you make a demo available for a look at how it works? Thx!!

**Comment by jasonroyle** [comment]
I will be trying to get an update and demo sorted this weekend. I'll keep you posted!

**Comment by jasonroyle** [comment]
Hey @fxcosta, I have pushed a couple of updates and written a [demo](https://plnkr.co/edit/Xwn1Z8HLDgQRwWwdXfoT?p=preview) that I have added to the [readme](https://github.com/jasonroyle/ng2-img-map/blob/master/README.md), check it out!

**Comment by fxcosta** [comment]
Awesome!! That's exactly what I needed. Thanks!!!
